on:
  push:
    branches:
      - main

name: release-plz
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: install protobuf compiler
        uses: arduino/setup-protoc@v1
        with:
          version: '3.20.2'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
